spring:
  datasource:
    username: root
    password: 1408
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/welldex
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true
server:
  port: 8010